name: CI

on:
    push:
    pull_request:

jobs:
    check-spelling:
        name: Check spelling
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/analyze/spell@master
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.23.x
                  cache-dependency-path: go.mod
            - name: Install dependencies
              run: go mod tidy
            - name: Build
              run: go build -v ./...
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.23.x
                  cache-dependency-path: go.mod
            - name: Install dependencies
              run: go mod tidy
            - name: Test
              run: go test
